import time

import MetaTrader5 as mt5
import pandas as pd
import smtplib
from email.mime.text import MIMEText
import configparser
config = configparser.ConfigParser()
config.read('mt5_settings.ini') #path of your .ini file

global smtp_server, login, password, port, sender_email, receiver_email, message

class Bot:

    # Email Configuration

    port = 587
    smtp_server = "smtp.hostinger.com"
    login = "notification@johanhartono.com"  # Your login generated by Mailtrap
    password = "Jolin@2021"  # Your password generated by Mailtrap

    sender_email = "notification@johanhartono.com"
    receiver_email = "johanhartono@gmail.com"






# Start of Functions

    def __init__(self,n,symbol,volume,profit_target,proportion):
        self.n = n
        self.symbol = symbol
        self.volume = volume
        self.profit_target = profit_target
        self.proportion = proportion

    # Buy Limit configuration
    def buy_limit(self,symbol, volume, price):
        request = mt5.order_send({
            "action": mt5.TRADE_ACTION_PENDING,
            "symbol": symbol,
            "volume": volume,
            "type": mt5.ORDER_TYPE_BUY_LIMIT,
            "price": price,
            "deviation": 20,
            "magic": 100,
            "comment": "python market order",
            "type_time": mt5.ORDER_TIME_GTC,
            "type_filling": mt5.ORDER_FILLING_IOC,
        })

        print(request)

    def sell_limit(self,symbol, volume, price):
        request = mt5.order_send({
            "action": mt5.TRADE_ACTION_PENDING,
            "symbol": symbol,
            "volume": volume,
            "type": mt5.ORDER_TYPE_SELL_LIMIT,
            "price": price,
            "deviation": 20,
            "magic": 100,
            "comment": "python market order",
            "type_time": mt5.ORDER_TIME_GTC,
            "type_filling": mt5.ORDER_FILLING_IOC,
        })

        print(request)

    def cal_profit(self,symbol):
        usd_positions = mt5.positions_get(symbol=symbol)
        df = pd.DataFrame(list(usd_positions), columns=usd_positions[0]._asdict().keys())
        df['time'] = pd.to_datetime(df['time'], unit='s')
        df.drop(['time_update', 'time_msc', 'time_update_msc', 'external_id'], axis=1, inplace=True)
        profit = float(df["profit"].sum())
        return profit

    def cal_volume(self,symbol):
        usd_positions = mt5.positions_get(symbol=symbol)
        df = pd.DataFrame(list(usd_positions), columns=usd_positions[0]._asdict().keys())
        df['time'] = pd.to_datetime(df['time'], unit='s')
        df.drop(['time_update', 'time_msc', 'time_update_msc', 'external_id'], axis=1, inplace=True)
        profit = float(df["volume"].sum())
        return profit

    def cal_buy_profit(self,symbol):
        usd_positions = mt5.positions_get(symbol=symbol)
        df = pd.DataFrame(list(usd_positions), columns=usd_positions[0]._asdict().keys())
        df['time'] = pd.to_datetime(df['time'], unit='s')
        df.drop(['time_update', 'time_msc', 'time_update_msc', 'external_id'], axis=1, inplace=True)
        df = df.loc[df.type == 0]
        profit = float(df["profit"].sum())
        return profit

    def cal_sell_profit(self,symbol):
        usd_positions = mt5.positions_get(symbol=symbol)
        df = pd.DataFrame(list(usd_positions), columns=usd_positions[0]._asdict().keys())
        df['time'] = pd.to_datetime(df['time'], unit='s')
        df.drop(['time_update', 'time_msc', 'time_update_msc', 'external_id'], axis=1, inplace=True)
        df = df.loc[df.type == 1]
        profit = float(df["profit"].sum())
        return profit

    def cal_buy_margin(self,symbol):
        usd_positions = mt5.positions_get(symbol=symbol)
        df = pd.DataFrame(list(usd_positions), columns=usd_positions[0]._asdict().keys())
        df['time'] = pd.to_datetime(df['time'], unit='s')
        df.drop(['time_update', 'time_msc', 'time_update_msc', 'external_id'], axis=1, inplace=True)
        df = df.loc[df.type == 0]

        sum = 0
        for i in df.index:
            volume = df.volume[i]
            open_price = df.price_open[i]
            margin = mt5.order_calc_margin(mt5.ORDER_TYPE_BUY, symbol, volume, open_price)
            sum += margin
        return sum

    def cal_sell_margin(self,symbol):
        usd_positions = mt5.positions_get(symbol=symbol)
        df = pd.DataFrame(list(usd_positions), columns=usd_positions[0]._asdict().keys())
        df['time'] = pd.to_datetime(df['time'], unit='s')
        df.drop(['time_update', 'time_msc', 'time_update_msc', 'external_id'], axis=1, inplace=True)
        df = df.loc[df.type == 1]

        sum = 0
        for i in df.index:
            volume = df.volume[i]
            open_price = df.price_open[i]
            margin = mt5.order_calc_margin(mt5.ORDER_TYPE_SELL, symbol, volume, open_price)
            sum += margin
        return sum

    def cal_pct_buy_profit(self,symbol):
        profit = self.cal_buy_profit(symbol)
        margin = self.cal_buy_margin(symbol)
        pct = (profit / margin) * 100
        return pct

    def cal_pct_sell_profit(self,symbol):
        profit = self.cal_sell_profit(symbol)
        margin = self.cal_sell_margin(symbol)
        pct = (profit / margin) * 100
        return pct

    def close_position(self,position):
        tick = mt5.symbol_info_tick(position.symbol)

        request = {
            "action": mt5.TRADE_ACTION_DEAL,
            "position": position.ticket,
            "symbol": position.symbol,
            "volume": position.volume,
            "type": mt5.ORDER_TYPE_BUY if position.type == 1 else mt5.ORDER_TYPE_SELL,
            "price": tick.ask if position.type == 1 else tick.bid,
            "deviation": 20,
            "magic": 100,
            "comment": "python script close",
            "type_time": mt5.ORDER_TIME_GTC,
            "type_filling": mt5.ORDER_FILLING_IOC,
        }

        result = mt5.order_send(request)
        return result

    def close_all(self,symbol):
        position = mt5.positions_get(symbol=symbol)
        for position in position:
            self.close_position(position)

    def delete_pending(self,ticket):
        close_request = {
            "action": mt5.TRADE_ACTION_REMOVE,
            "order": ticket,
            "type_time": mt5.ORDER_TIME_GTC,
            "type_filling": mt5.ORDER_FILLING_IOC,
        }
        result = mt5.order_send(close_request)

        if result.retcode != mt5.TRADE_RETCODE_DONE:
            result_dict = result._asdict()
            print(result_dict)
        else:
            print('Delete complete...')

    def close_limit(self,symbol):
        orders = mt5.orders_get(symbol=symbol)
        df = pd.DataFrame(list(orders), columns=orders[0]._asdict().keys())
        df.drop(['time_done', 'time_done_msc', 'position_id', 'position_by_id', 'reason', 'volume_initial',
                 'price_stoplimit'], axis=1, inplace=True)
        df['time_setup'] = pd.to_datetime(df['time_setup'], unit='s')
        for ticket in df.ticket:
            self.delete_pending(ticket)

# End of Functions

# Engine - Running Bots
    def run(self):
        #############################################################################################################
        symboly = config.get("Settings", "symbol")
        max_lossy = int(config.get("Settings", "max_loss_all_trade"))
        max_profity = int(config.get("Settings", "max_profit_all_trade"))
        from_warningy = int(config.get("Settings", "from_warning"))
        to_warningy = int(config.get("Settings", "to_warning"))
        from_notify = int(config.get("Settings", "from_notif"))
        to_notify = int(config.get("Settings", "to_notif"))
        bot_typey = config.get("Settings","bot_type")
        only_cl_tpy = int(config.get("Settings","only_cl_tp"))
        lowest_pricey = float(config.get("Settings","lowest_price"))
        highest_pricey = float(config.get("Settings", "highest_price"))
        print("Trading Symbol:" + symboly, "Maximum Loss:" + str(max_lossy), "Maximum Profit:" + str(max_profity))
        print("Bot Type:" + str(bot_typey))
        print("Bot is running!")

        #############################################################################################################


        #######################################Srategy Hedging Bot###################################################
        while True:
            if only_cl_tpy == 0:
                pct_change = -1
                tick = mt5.symbol_info_tick(self.symbol)
                current_price_sell = tick.bid
                adj_sell = 1.2

                for i in range(self.n):
                    price = ((pct_change / (100 * 100)) * current_price_sell) * adj_sell * self.proportion + current_price_sell
                    #print(price)
                    self.sell_limit(self.symbol, self.volume, price)
                    pct_change += 1
                    adj_sell += 1.2


                pct_change_2 = 1
                tick = mt5.symbol_info_tick(self.symbol)
                current_price_buy = tick.ask
                adj_buy = 1.2

                for i in range(self.n):
                    price = ((pct_change_2 / (100 * 100)) * current_price_buy) * adj_buy * self.proportion + current_price_buy
                    self.buy_limit(self.symbol, self.volume, price)
                    pct_change_2 -= 1
                    adj_buy += 1.2



            while True:
                #################################TP and SL ##########################################
                #position = mt5.positions_get(symbol=self.symbol)
                symbol_list = open("symbols.txt", "r")
                current_account_info = mt5.account_info()
                current_balance_info = mt5.account_info().balance
                time.sleep(0.2)
                #print(position)
                stry = current_account_info.profit,current_balance_info,current_balance_info+current_account_info.profit
                with open('logs.txt', 'a') as f:
                    f.write(repr(stry) + '\n')
                #print (current_account_info.profit,current_balance_info,current_balance_info+current_account_info.profit)
                #print('Running Profit' + current_account_info.profit, 'Capital' + str(capitaly),
                #'Rem Bal' + str(capitaly + current_account_info.profit))

                #Notification
                #print(current_account_info.profit,from_warningy,to_warningy)
                if float(current_account_info.profit)  <= from_warningy and current_account_info.profit >=to_warningy:
                    try:

                        print("Alert floating Loss going to Loss!--->  " + str(current_account_info.profit) + " Max Losses: " + str(max_lossy))

                    except:
                        break
                #Notification
                elif float(current_account_info.profit)  >=from_notify and current_account_info.profit <=to_notify:
                    try:

                        print("Alert floating Profit going to Profit!--->  " + str(current_account_info.profit) + " Max Profit: " + str(max_profity))

                    except:
                        break
                else:
                    time.sleep(2)
                    print("Awaiting")

                # Max Loss
                if current_account_info.profit  <= max_lossy:
                    if only_cl_tpy == 1:
                        try:
                            positions = mt5.positions_get()

                            # Close all open positions
                            for position in positions:
                                mt5.Close(symbol='AUDCAD', ticket=position.ticket)
                                mt5.Close(symbol='AUDCHF', ticket=position.ticket)
                                mt5.Close(symbol='AUDJPY', ticket=position.ticket)
                                mt5.Close(symbol='AUDNZD', ticket=position.ticket)
                                mt5.Close(symbol='AUDUSD', ticket=position.ticket)
                                mt5.Close(symbol='BTCUSD', ticket=position.ticket)
                                mt5.Close(symbol='CADCHF', ticket=position.ticket)
                                mt5.Close(symbol='CADJPY', ticket=position.ticket)
                                mt5.Close(symbol='CHFJPY', ticket=position.ticket)
                                mt5.Close(symbol='ETHUSD', ticket=position.ticket)
                                mt5.Close(symbol='EURAUD', ticket=position.ticket)
                                mt5.Close(symbol='EURCAD', ticket=position.ticket)
                                mt5.Close(symbol='EURCHF', ticket=position.ticket)
                                mt5.Close(symbol='EURGBP', ticket=position.ticket)
                                mt5.Close(symbol='EURJPY', ticket=position.ticket)
                                mt5.Close(symbol='EURNZD', ticket=position.ticket)
                                mt5.Close(symbol='EURUSD', ticket=position.ticket)
                                mt5.Close(symbol='GBPAUD', ticket=position.ticket)
                                mt5.Close(symbol='GBPCAD', ticket=position.ticket)
                                mt5.Close(symbol='GBPCHF', ticket=position.ticket)
                                mt5.Close(symbol='GBPJPY', ticket=position.ticket)
                                mt5.Close(symbol='GBPNZD', ticket=position.ticket)
                                mt5.Close(symbol='GBPUSD', ticket=position.ticket)
                                mt5.Close(symbol='NZDCAD', ticket=position.ticket)
                                mt5.Close(symbol='NZDCHF', ticket=position.ticket)
                                mt5.Close(symbol='NZDJPY', ticket=position.ticket)
                                mt5.Close(symbol='NZDUSD', ticket=position.ticket)
                                mt5.Close(symbol='USDCAD', ticket=position.ticket)
                                mt5.Close(symbol='USDCHF', ticket=position.ticket)
                                mt5.Close(symbol='USDJPY', ticket=position.ticket)

                            # Shut down MetaTrader 5
                            print("Bot was stopped!")
                            print("Loss!!!, You are unlucky today!")
                            mt5.shutdown()

                        except:
                                break
                    else:
                        try:
                             mt5.Close(symboly)
                             self.close_limit(symboly)
                             with open('logs.txt', 'a') as f:
                                 f.write(repr("Unfortunately, You are unlucky Today!") + '\n')
                             print("Bot was stopped!")
                             print("Profit!!!, You are lucky today!")
                             mt5.shutdown()
                        except:
                                break
                # Max Profit
                if current_account_info.profit >= max_profity:
                    if only_cl_tpy == 1:
                        try:
                            positions = mt5.positions_get()

                            # Close all open positions
                            for position in positions:
                                mt5.Close(symbol='AUDCAD', ticket=position.ticket)
                                mt5.Close(symbol='AUDCHF', ticket=position.ticket)
                                mt5.Close(symbol='AUDJPY', ticket=position.ticket)
                                mt5.Close(symbol='AUDNZD', ticket=position.ticket)
                                mt5.Close(symbol='AUDUSD', ticket=position.ticket)
                                mt5.Close(symbol='BTCUSD', ticket=position.ticket)
                                mt5.Close(symbol='CADCHF', ticket=position.ticket)
                                mt5.Close(symbol='CADJPY', ticket=position.ticket)
                                mt5.Close(symbol='CHFJPY', ticket=position.ticket)
                                mt5.Close(symbol='ETHUSD', ticket=position.ticket)
                                mt5.Close(symbol='EURAUD', ticket=position.ticket)
                                mt5.Close(symbol='EURCAD', ticket=position.ticket)
                                mt5.Close(symbol='EURCHF', ticket=position.ticket)
                                mt5.Close(symbol='EURGBP', ticket=position.ticket)
                                mt5.Close(symbol='EURJPY', ticket=position.ticket)
                                mt5.Close(symbol='EURNZD', ticket=position.ticket)
                                mt5.Close(symbol='EURUSD', ticket=position.ticket)
                                mt5.Close(symbol='GBPAUD', ticket=position.ticket)
                                mt5.Close(symbol='GBPCAD', ticket=position.ticket)
                                mt5.Close(symbol='GBPCHF', ticket=position.ticket)
                                mt5.Close(symbol='GBPJPY', ticket=position.ticket)
                                mt5.Close(symbol='GBPNZD', ticket=position.ticket)
                                mt5.Close(symbol='GBPUSD', ticket=position.ticket)
                                mt5.Close(symbol='NZDCAD', ticket=position.ticket)
                                mt5.Close(symbol='NZDCHF', ticket=position.ticket)
                                mt5.Close(symbol='NZDJPY', ticket=position.ticket)
                                mt5.Close(symbol='NZDUSD', ticket=position.ticket)
                                mt5.Close(symbol='USDCAD', ticket=position.ticket)
                                mt5.Close(symbol='USDCHF', ticket=position.ticket)
                                mt5.Close(symbol='USDJPY', ticket=position.ticket)

                            # Shut down MetaTrader 5
                            print("Bot was stopped!")
                            print("Profit!!!")
                            mt5.shutdown()

                        except:
                                break
                    else:
                        try:

                            mt5.Close(symboly)
                            self.close_limit(symboly)
                            with open('logs.txt', 'a') as f:
                                f.write(repr("Profit!!!!!!!") + '\n')
                            print("Bot was stopped!")
                            mt5.shutdown()
                        except:
                            break

                #Break out Over RSI Highest or Lowest
                ticks = mt5.symbol_info_tick(self.symbol)
                current_price_sells = ticks.bid
                current_price_buys = ticks.ask
                if current_price_sells <=  lowest_pricey:
                     try:
                         mt5.Close(symboly)
                     except:
                         break
                if current_price_buys >=  highest_pricey:
                     try:
                         mt5.Close(symboly)
                     except:
                         break
                #################################TP and SL ##########################################

                # if len(position) > 0:
                #     margin_s = self.cal_sell_margin(self.symbol)
                #     margin_b = self.cal_buy_margin(self.symbol)
                #
                #     if margin_s > 0:
                #         try:
                #             pct_sell_profit = self.cal_pct_sell_profit(self.symbol)
                #             if pct_sell_profit >= self.profit_target:
                #                 self.close_all(self.symbol)
                #         except:
                #             pass
                #
                #     if margin_b > 0:
                #         try:
                #             pct_buy_profit = self.cal_pct_buy_profit(self.symbol)
                #             if pct_buy_profit >= self.profit_target:
                #                 self.close_all(self.symbol)
                #         except:
                #             pass
                #
                #     position = mt5.positions_get(symbol=self.symbol)
                #     if len(position) == 0:
                #         self.close_limit(self.symbol)
                #         break

        #######################################Srategy Hedging Bot###################################################