import smtplib
from email.mime.text import MIMEText

# Configuration
port = 587
smtp_server = "smtp.hostinger.com"
login = "notification@johanhartono.com"  # Your login generated by Mailtrap
password = "Jolin@2021"  # Your password generated by Mailtrap

sender_email = "notification@johanhartono.com"
receiver_email = "johanhartono@gmail.com"

# Plain text content
text = """\
Hi,Trader. Profit reach USD 1 Completed
"""

# Create MIMEText object
message = MIMEText(text, "plain")
message["Subject"] = "Plain text email"
message["From"] = sender_email
message["To"] = receiver_email

# Send the email
with smtplib.SMTP(smtp_server, port) as server:
    server.starttls()  # Secure the connection
    server.login(login, password)
    server.sendmail(sender_email, receiver_email, message.as_string())

print('Sent')